// This file is generated by rust-protobuf 3.4.0. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `encrypted_app_ticket.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_4_0;

// @@protoc_insertion_point(message:EncryptedAppTicket)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct EncryptedAppTicket {
    // message fields
    // @@protoc_insertion_point(field:EncryptedAppTicket.ticket_version_no)
    pub ticket_version_no: ::std::option::Option<u32>,
    // @@protoc_insertion_point(field:EncryptedAppTicket.crc_encryptedticket)
    pub crc_encryptedticket: ::std::option::Option<u32>,
    // @@protoc_insertion_point(field:EncryptedAppTicket.cb_encrypteduserdata)
    pub cb_encrypteduserdata: ::std::option::Option<u32>,
    // @@protoc_insertion_point(field:EncryptedAppTicket.cb_encrypted_appownershipticket)
    pub cb_encrypted_appownershipticket: ::std::option::Option<u32>,
    // @@protoc_insertion_point(field:EncryptedAppTicket.encrypted_ticket)
    pub encrypted_ticket: ::std::option::Option<::std::vec::Vec<u8>>,
    // special fields
    // @@protoc_insertion_point(special_field:EncryptedAppTicket.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a EncryptedAppTicket {
    fn default() -> &'a EncryptedAppTicket {
        <EncryptedAppTicket as ::protobuf::Message>::default_instance()
    }
}

impl EncryptedAppTicket {
    pub fn new() -> EncryptedAppTicket {
        ::std::default::Default::default()
    }

    // optional uint32 ticket_version_no = 1;

    pub fn ticket_version_no(&self) -> u32 {
        self.ticket_version_no.unwrap_or(0)
    }

    pub fn clear_ticket_version_no(&mut self) {
        self.ticket_version_no = ::std::option::Option::None;
    }

    pub fn has_ticket_version_no(&self) -> bool {
        self.ticket_version_no.is_some()
    }

    // Param is passed by value, moved
    pub fn set_ticket_version_no(&mut self, v: u32) {
        self.ticket_version_no = ::std::option::Option::Some(v);
    }

    // optional uint32 crc_encryptedticket = 2;

    pub fn crc_encryptedticket(&self) -> u32 {
        self.crc_encryptedticket.unwrap_or(0)
    }

    pub fn clear_crc_encryptedticket(&mut self) {
        self.crc_encryptedticket = ::std::option::Option::None;
    }

    pub fn has_crc_encryptedticket(&self) -> bool {
        self.crc_encryptedticket.is_some()
    }

    // Param is passed by value, moved
    pub fn set_crc_encryptedticket(&mut self, v: u32) {
        self.crc_encryptedticket = ::std::option::Option::Some(v);
    }

    // optional uint32 cb_encrypteduserdata = 3;

    pub fn cb_encrypteduserdata(&self) -> u32 {
        self.cb_encrypteduserdata.unwrap_or(0)
    }

    pub fn clear_cb_encrypteduserdata(&mut self) {
        self.cb_encrypteduserdata = ::std::option::Option::None;
    }

    pub fn has_cb_encrypteduserdata(&self) -> bool {
        self.cb_encrypteduserdata.is_some()
    }

    // Param is passed by value, moved
    pub fn set_cb_encrypteduserdata(&mut self, v: u32) {
        self.cb_encrypteduserdata = ::std::option::Option::Some(v);
    }

    // optional uint32 cb_encrypted_appownershipticket = 4;

    pub fn cb_encrypted_appownershipticket(&self) -> u32 {
        self.cb_encrypted_appownershipticket.unwrap_or(0)
    }

    pub fn clear_cb_encrypted_appownershipticket(&mut self) {
        self.cb_encrypted_appownershipticket = ::std::option::Option::None;
    }

    pub fn has_cb_encrypted_appownershipticket(&self) -> bool {
        self.cb_encrypted_appownershipticket.is_some()
    }

    // Param is passed by value, moved
    pub fn set_cb_encrypted_appownershipticket(&mut self, v: u32) {
        self.cb_encrypted_appownershipticket = ::std::option::Option::Some(v);
    }

    // optional bytes encrypted_ticket = 5;

    pub fn encrypted_ticket(&self) -> &[u8] {
        match self.encrypted_ticket.as_ref() {
            Some(v) => v,
            None => &[],
        }
    }

    pub fn clear_encrypted_ticket(&mut self) {
        self.encrypted_ticket = ::std::option::Option::None;
    }

    pub fn has_encrypted_ticket(&self) -> bool {
        self.encrypted_ticket.is_some()
    }

    // Param is passed by value, moved
    pub fn set_encrypted_ticket(&mut self, v: ::std::vec::Vec<u8>) {
        self.encrypted_ticket = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_encrypted_ticket(&mut self) -> &mut ::std::vec::Vec<u8> {
        if self.encrypted_ticket.is_none() {
            self.encrypted_ticket = ::std::option::Option::Some(::std::vec::Vec::new());
        }
        self.encrypted_ticket.as_mut().unwrap()
    }

    // Take field
    pub fn take_encrypted_ticket(&mut self) -> ::std::vec::Vec<u8> {
        self.encrypted_ticket.take().unwrap_or_else(|| ::std::vec::Vec::new())
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "ticket_version_no",
            |m: &EncryptedAppTicket| { &m.ticket_version_no },
            |m: &mut EncryptedAppTicket| { &mut m.ticket_version_no },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "crc_encryptedticket",
            |m: &EncryptedAppTicket| { &m.crc_encryptedticket },
            |m: &mut EncryptedAppTicket| { &mut m.crc_encryptedticket },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "cb_encrypteduserdata",
            |m: &EncryptedAppTicket| { &m.cb_encrypteduserdata },
            |m: &mut EncryptedAppTicket| { &mut m.cb_encrypteduserdata },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "cb_encrypted_appownershipticket",
            |m: &EncryptedAppTicket| { &m.cb_encrypted_appownershipticket },
            |m: &mut EncryptedAppTicket| { &mut m.cb_encrypted_appownershipticket },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "encrypted_ticket",
            |m: &EncryptedAppTicket| { &m.encrypted_ticket },
            |m: &mut EncryptedAppTicket| { &mut m.encrypted_ticket },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<EncryptedAppTicket>(
            "EncryptedAppTicket",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for EncryptedAppTicket {
    const NAME: &'static str = "EncryptedAppTicket";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.ticket_version_no = ::std::option::Option::Some(is.read_uint32()?);
                },
                16 => {
                    self.crc_encryptedticket = ::std::option::Option::Some(is.read_uint32()?);
                },
                24 => {
                    self.cb_encrypteduserdata = ::std::option::Option::Some(is.read_uint32()?);
                },
                32 => {
                    self.cb_encrypted_appownershipticket = ::std::option::Option::Some(is.read_uint32()?);
                },
                42 => {
                    self.encrypted_ticket = ::std::option::Option::Some(is.read_bytes()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.ticket_version_no {
            my_size += ::protobuf::rt::uint32_size(1, v);
        }
        if let Some(v) = self.crc_encryptedticket {
            my_size += ::protobuf::rt::uint32_size(2, v);
        }
        if let Some(v) = self.cb_encrypteduserdata {
            my_size += ::protobuf::rt::uint32_size(3, v);
        }
        if let Some(v) = self.cb_encrypted_appownershipticket {
            my_size += ::protobuf::rt::uint32_size(4, v);
        }
        if let Some(v) = self.encrypted_ticket.as_ref() {
            my_size += ::protobuf::rt::bytes_size(5, &v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.ticket_version_no {
            os.write_uint32(1, v)?;
        }
        if let Some(v) = self.crc_encryptedticket {
            os.write_uint32(2, v)?;
        }
        if let Some(v) = self.cb_encrypteduserdata {
            os.write_uint32(3, v)?;
        }
        if let Some(v) = self.cb_encrypted_appownershipticket {
            os.write_uint32(4, v)?;
        }
        if let Some(v) = self.encrypted_ticket.as_ref() {
            os.write_bytes(5, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> EncryptedAppTicket {
        EncryptedAppTicket::new()
    }

    fn clear(&mut self) {
        self.ticket_version_no = ::std::option::Option::None;
        self.crc_encryptedticket = ::std::option::Option::None;
        self.cb_encrypteduserdata = ::std::option::Option::None;
        self.cb_encrypted_appownershipticket = ::std::option::Option::None;
        self.encrypted_ticket = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static EncryptedAppTicket {
        static instance: EncryptedAppTicket = EncryptedAppTicket {
            ticket_version_no: ::std::option::Option::None,
            crc_encryptedticket: ::std::option::Option::None,
            cb_encrypteduserdata: ::std::option::Option::None,
            cb_encrypted_appownershipticket: ::std::option::Option::None,
            encrypted_ticket: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for EncryptedAppTicket {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("EncryptedAppTicket").unwrap()).clone()
    }
}

impl ::std::fmt::Display for EncryptedAppTicket {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for EncryptedAppTicket {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1aencrypted_app_ticket.proto\"\x97\x02\n\x12EncryptedAppTicket\x12*\
    \n\x11ticket_version_no\x18\x01\x20\x01(\rR\x0fticketVersionNo\x12/\n\
    \x13crc_encryptedticket\x18\x02\x20\x01(\rR\x12crcEncryptedticket\x121\n\
    \x14cb_encrypteduserdata\x18\x03\x20\x01(\rR\x13cbEncrypteduserdata\x12F\
    \n\x1fcb_encrypted_appownershipticket\x18\x04\x20\x01(\rR\x1dcbEncrypted\
    Appownershipticket\x12)\n\x10encrypted_ticket\x18\x05\x20\x01(\x0cR\x0fe\
    ncryptedTicketB\x05H\x01\x80\x01\0J\xa3\x03\n\x06\x12\x04\0\0\t\x01\n\
    \x08\n\x01\x08\x12\x03\0\0\x1c\n\t\n\x02\x08\t\x12\x03\0\0\x1c\n\x08\n\
    \x01\x08\x12\x03\x01\0#\n\t\n\x02\x08\x10\x12\x03\x01\0#\n\n\n\x02\x04\0\
    \x12\x04\x03\0\t\x01\n\n\n\x03\x04\0\x01\x12\x03\x03\x08\x1a\n\x0b\n\x04\
    \x04\0\x02\0\x12\x03\x04\x08.\n\x0c\n\x05\x04\0\x02\0\x04\x12\x03\x04\
    \x08\x10\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\x04\x11\x17\n\x0c\n\x05\x04\
    \0\x02\0\x01\x12\x03\x04\x18)\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x04,-\
    \n\x0b\n\x04\x04\0\x02\x01\x12\x03\x05\x080\n\x0c\n\x05\x04\0\x02\x01\
    \x04\x12\x03\x05\x08\x10\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\x05\x11\
    \x17\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\x05\x18+\n\x0c\n\x05\x04\0\
    \x02\x01\x03\x12\x03\x05./\n\x0b\n\x04\x04\0\x02\x02\x12\x03\x06\x081\n\
    \x0c\n\x05\x04\0\x02\x02\x04\x12\x03\x06\x08\x10\n\x0c\n\x05\x04\0\x02\
    \x02\x05\x12\x03\x06\x11\x17\n\x0c\n\x05\x04\0\x02\x02\x01\x12\x03\x06\
    \x18,\n\x0c\n\x05\x04\0\x02\x02\x03\x12\x03\x06/0\n\x0b\n\x04\x04\0\x02\
    \x03\x12\x03\x07\x08<\n\x0c\n\x05\x04\0\x02\x03\x04\x12\x03\x07\x08\x10\
    \n\x0c\n\x05\x04\0\x02\x03\x05\x12\x03\x07\x11\x17\n\x0c\n\x05\x04\0\x02\
    \x03\x01\x12\x03\x07\x187\n\x0c\n\x05\x04\0\x02\x03\x03\x12\x03\x07:;\n\
    \x0b\n\x04\x04\0\x02\x04\x12\x03\x08\x08,\n\x0c\n\x05\x04\0\x02\x04\x04\
    \x12\x03\x08\x08\x10\n\x0c\n\x05\x04\0\x02\x04\x05\x12\x03\x08\x11\x16\n\
    \x0c\n\x05\x04\0\x02\x04\x01\x12\x03\x08\x17'\n\x0c\n\x05\x04\0\x02\x04\
    \x03\x12\x03\x08*+\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(EncryptedAppTicket::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
